{% from 'macros/header.j2' import header with context %}
{{ header('#') }}

ARG IMAGE_CI

FROM ${IMAGE_CI}-dev

USER root

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
    apt-get update && apt-get install -y google-chrome-stable

USER node
