{% extends '_/es/Makefile.j2' %}

{% block lint %}
{% endblock %}

{% block clean %}
{{ super() }}
	rm -f app.js
	rm -rf app/js
	rm -rf test/unit/js
	rm -rf test/acceptance/js
{% endblock %}

{% block test %}
test: test_unit test_acceptance
{% endblock %}

{% block build_app %}
build_app:
	npm run compile:all
{% endblock %}
