{% extends '_/es/Makefile.j2' %}

{% block lint %}
{% endblock %}

{% block clean %}
{{ super() }}
	rm -f app.js
	rm -f app.map
	rm -rf app/js
	rm -rf test/acceptance/js
	rm -rf test/load/js
	rm -rf test/smoke/js
	rm -rf test/unit/js
{% endblock %}

{% block test %}
test: test_unit test_acceptance
{% endblock %}

{% block build_app %}
build_app: compile_app
build_app: compile_tests

compile_app: compile/app.coffee compile/app/coffee

TEST_COFFEE_SOURCES := $(addprefix compile/,$(wildcard test/*/coffee))
compile_tests: $(TEST_COFFEE_SOURCES)

COMPILE_COFFEE_DIRS := \
	compile/app/coffee \
	$(TEST_COFFEE_SOURCES)

$(COMPILE_COFFEE_DIRS): compile/%coffee:
	npx coffee --map --output $*js --compile $*coffee

compile/app.coffee:
	npx coffee --map --compile app.coffee
{% endblock %}
