{% extends '_/es/Dockerfile.j2' %}

{% block volumes %}
VOLUME \
    {{ [
        '/app/public_files',
        '/app/template_files',
        '/app/user_files',
    ]|join(' \\\n    ') }}
{% endblock %}
