{% extends '_/es/Dockerfile.j2' %}

{% block runtime %}
{{ super() }}
VOLUME \
    {{ [
        '/app/public_files',
        '/app/template_files',
        '/app/user_files',
    ]|join(' \\\n    ') }}
{% endblock %}
