{% extends '_/es/Makefile.j2' %}


{% block test_acceptance %}
test_acceptance_app_run: test_acceptance_fs_run
test_acceptance_app_run: clean_test_acceptance
test_acceptance_app_run: test_acceptance_s3_run

test_acceptance_fs: clean_test_acceptance
test_acceptance_fs: test_acceptance_fs_run
test_acceptance_s3: clean_test_acceptance
test_acceptance_s3: test_acceptance_s3_run

test_acceptance_fs_run:
	BACKEND=fs $(ACCEPTANCE_TEST_DOCKER_COMPOSE) run --rm test_acceptance \
		output=/home/node/acceptance_fs.xml,suiteName='FS Acceptance Tests' \
		test/acceptance/js

test_acceptance_s3_run:
	BACKEND=s3 $(ACCEPTANCE_TEST_DOCKER_COMPOSE) run --rm test_acceptance \
		output=/home/node/acceptance_s3.xml,suiteName='S3 Acceptance Tests' \
		test/acceptance/js
{% endblock %}
