{% from 'macros/header.j2' import header with context %}
{{ header('#') }}

ARG BASE
FROM $BASE

{% if monkey_patch_npm_ci__from %}
# monkey patch npm ci --only=prod
# npm tries to update the _from field of dev-only/optional dependencies
RUN sed -i -E \
      's/(updateFromField .+)/\1\n    return Promise.resolve()/' \
      /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js
{% endif %}

RUN /docker_cleanup.sh npm ci --only=prod

ADD build_artifacts.tar.gz /app

{% if has_setup_env %}
RUN /app/setup_env.sh
{% endif -%}

{% if data_dirs %}
RUN DATA_DIRS="{{ data_dirs|join(' ') }}" \
&&  mkdir -p ${DATA_DIRS} \
&&  chown node:node ${DATA_DIRS}
{% endif %}

{% block volumes %}
{% endblock %}

{% if not has_entrypoint %}
USER node
{% endif %}

ARG RELEASE
ARG COMMIT
ENV \
    SERVICE_NAME="{{ name }}" \
    RELEASE=${RELEASE} \
    SENTRY_RELEASE=${RELEASE} \
    COMMIT=${COMMIT}

{# monkey patch for https://github.com/moby/moby/issues/37273 #}
CMD ["node", "--expose-gc", "{{ 'index' if has_index_js else 'app' }}.js"]
