FROM node:{{ node_version }} as app

{% block app %}
WORKDIR /app

#wildcard as some files may not be in all repos
COPY package*.json npm-shrink*.json /app/

RUN npm install --quiet

COPY . /app


{% endblock %}

FROM node:{{ node_version }}

{% block runtime %}
CMD ["node", "--expose-gc", "app.js"]

WORKDIR /app

{% if has_entrypoint %}
ENTRYPOINT ["/bin/sh", "entrypoint.sh"]
{% endif %}

{% if has_install_deps %}
COPY install_deps.sh /app
RUN /app/install_deps.sh
{% endif %}

COPY --from=app /app /app

{% if has_setup_env %}
RUN /app/setup_env.sh

{% endif -%}

{% if not has_entrypoint %}
USER node
{% endif %}
{% endblock %}

ARG RELEASE
ARG COMMIT
ENV RELEASE=${RELEASE} \
    SENTRY_RELEASE=${RELEASE} \
    COMMIT=${COMMIT}
