{% from 'macros/header.j2' import header with context %}
{{ header('#') }}

FROM node:{{ node_version }} AS base

CMD ["node", "--expose-gc", "{{ 'index' if has_index_js else 'app' }}.js"]

{% if has_entrypoint %}
ENTRYPOINT ["/bin/sh", "entrypoint.sh"]
{% endif %}

WORKDIR /app

COPY docker_cleanup.sh /

{% if has_install_deps %}
COPY install_deps.sh /app/
RUN /app/install_deps.sh
{% endif %}

COPY package.json package-lock.json /app/


FROM base AS dev

RUN /docker_cleanup.sh npm ci

COPY . /app

RUN /docker_cleanup.sh make build_app

{% if has_setup_env %}
RUN /app/setup_env.sh
{% endif -%}

{% if data_dirs %}
RUN DATA_DIRS="{{ data_dirs|join(' ') }}" \
&&  mkdir -p ${DATA_DIRS} \
&&  chown node:node ${DATA_DIRS}
{% endif %}

{% if not has_entrypoint %}
USER node
{% endif %}

{% if has_webpack_config_js %}
FROM dev as webpack
USER root
RUN /docker_cleanup.sh npm run webpack:production
{% endif %}
