{% from 'macros/header.j2' import header with context %}
{{ header('#') }}

ifneq (,$(wildcard .git))
git = git
else
# we are in docker, without the .git directory
git = sh -c 'false'
endif

PWD ?= $(shell pwd)
SUDO_UID ?= $(shell id -u)
SUDO_GID ?= $(shell id -g)

export BUILD_NUMBER ?= local
export BRANCH_NAME ?= $(shell $(git) rev-parse --abbrev-ref HEAD || echo master)
export COMMIT ?= $(shell $(git) rev-parse HEAD || echo HEAD)
export RELEASE ?= \
	$(shell $(git) describe --tags || echo v0.0.0 | sed 's/-g/+/;s/^v//')
export PROJECT_NAME = {{ name }}
export BUILD_DIR_NAME = $(shell pwd | xargs basename | tr -cd '[a-zA-Z0-9_.\-]')
{% if 'minio' in dependencies %}
export AWS_S3_ENDPOINT ?= http://minio:9000
export AWS_S3_PATH_STYLE ?= true
DUMMY_AWS_ACCESS_KEY_ID := $(shell openssl rand -hex 20)
export AWS_ACCESS_KEY_ID ?= $(DUMMY_AWS_ACCESS_KEY_ID)
DUMMY_AWS_SECRET_ACCESS_KEY := $(shell openssl rand -hex 20)
export AWS_SECRET_ACCESS_KEY ?= $(DUMMY_AWS_SECRET_ACCESS_KEY)
{%   if name == 'filestore' %}
export AWS_BUCKET_USER ?= user
export AWS_BUCKET_TEMPLATE ?= template
export AWS_BUCKET_PUBLIC ?= public
{%   else %}
export AWS_BUCKET ?= bucket
{%   endif %}
{% endif %}
DOCKER_COMPOSE_FLAGS ?= -f docker-compose.yml
DOCKER_COMPOSE := docker-compose $(DOCKER_COMPOSE_FLAGS)

export DOCKER_REGISTRY ?= local
export SHARELATEX_DOCKER_REPOS ?= $(DOCKER_REGISTRY)/sharelatex

export IMAGE_NODE ?= $(DOCKER_REGISTRY)/node:{{ node_version }}
export IMAGE_PROJECT ?= $(SHARELATEX_DOCKER_REPOS)/$(PROJECT_NAME)
export IMAGE_BRANCH ?= $(IMAGE_PROJECT):$(BRANCH_NAME)
export IMAGE ?= $(IMAGE_BRANCH)-$(BUILD_NUMBER)

export IMAGE_BRANCH_DEV ?= $(IMAGE_PROJECT):dev
export IMAGE_CACHE_COLD ?= $(IMAGE_BRANCH_DEV)
export IMAGE_CACHE_HOT ?= $(IMAGE_BRANCH)

SUFFIX ?=
export IMAGE_CI ?= ci/$(PROJECT_NAME):$(BRANCH_NAME)-$(BUILD_NUMBER)$(SUFFIX)

# Helper for creating reproducible tartifacts
REFERENCE_DATE := 2020-01-01T00:00Z
TAR_FLAGS_REPRODUCIBLE := --sort=name --mtime=$(REFERENCE_DATE)
TAR_CREATE_REPRODUCIBLE := tar --create $(TAR_FLAGS_REPRODUCIBLE)
TOUCH_FLAGS_REPRODUCIBLE := -m -d $(REFERENCE_DATE)
TOUCH_REPRODUCIBLE := touch $(TOUCH_FLAGS_REPRODUCIBLE)

clean_ci: clean
clean_ci: clean_build

clean_build: clean_docker_images
clean_docker_images:
	docker rmi \
		$(IMAGE_CI)-base \
		$(IMAGE_CI)-dev-deps \
		$(IMAGE_CI)-dev \
		$(IMAGE_CI)-prod \
{% if has_webpack_config_js %}
		$(IMAGE_CI)-webpack \
{% endif %}
		$(IMAGE_CI)-dev-deps-cache \
		$(IMAGE_CI)-prod-cache \
		--force

clean:
{% block clean %}
{% endblock %}

test: lint
lint:
test: format
format:

{% block lint %}
{#
    - scenario 1
        some eslint dependency changed
        -> lint_full
        -> run the linter on all the source code files
    - scenario 2
        some source code file changed
        -> lint_partial
        -> run the linter on the changed files
    - scenario 3
        misc project files changed
        -> no op
        -> skip linting

    NOTE: the base line for the changed state is the last successful commit in
           CI or the dev branch - see below
#}
LINT_RUNNER_IMAGE ?= \
	$(SHARELATEX_DOCKER_REPOS)/lint-runner:{{ lint_runner_version }}
LINT_RUNNER = \
	docker run \
		--rm \
		--tty \
		--volume $(PWD):$(PWD) \
		--workdir $(PWD) \
		--user $(SUDO_UID):$(SUDO_GID) \
		$(LINT_RUNNER_IMAGE)

{# set by Jenkins, fall back to dev branch on current remote, then origin #}
GIT_PREVIOUS_SUCCESSFUL_COMMIT ?= $(shell \
{# requires a new git version, tested with 2.17.0, failed with 1.8.3 #}
	$(git) rev-parse --abbrev-ref --symbolic-full-name dev@{u} 2>/dev/null \
	| grep -e /dev \
	|| echo origin/dev)

NEED_FULL_LINT ?= \
	$(shell $(git) diff $(GIT_PREVIOUS_SUCCESSFUL_COMMIT) --name-only \
			| grep --max-count=1 \
				-e .eslintignore \
				-e .eslintrc \
				-e buildscript.txt \
	)

ifeq (,$(NEED_FULL_LINT))
lint: lint_partial
else
lint: lint_full
endif

RUN_LINT ?= $(LINT_RUNNER) eslint
lint_full:
	$(RUN_LINT) .

GIT_DIFF_CMD_FORMAT ?= \
	$(git) diff $(GIT_PREVIOUS_SUCCESSFUL_COMMIT) --name-only \
	| grep --invert-match \
		-e vendor \
	| grep \
		-e '\.js$$' \
{% if has_frontend_stylesheets %}
		-e '\.less$$' \
{% endif %}
	| sed 's|^|$(PWD)/|'

FILES_FOR_FORMAT ?= $(wildcard $(shell $(GIT_DIFF_CMD_FORMAT)))
{% if has_frontend_stylesheets %}
{# eslint can not parse .less files #}
FILES_FOR_LINT ?= $(wildcard $(shell $(GIT_DIFF_CMD_FORMAT) | grep -e '\.js$$'))
{% else %}
FILES_FOR_LINT ?= $(FILES_FOR_FORMAT)
{% endif %}

lint_partial:
ifneq (,$(FILES_FOR_LINT))
	$(RUN_LINT) $(FILES_FOR_LINT)
endif


NEED_FULL_FORMAT ?= \
	$(shell $(git) diff $(GIT_PREVIOUS_SUCCESSFUL_COMMIT) --name-only \
			| grep --max-count=1 \
				-e .prettierignore \
				-e .prettierrc \
				-e buildscript.txt \
	)

ifeq (,$(NEED_FULL_FORMAT))
format: format_partial
format_fix: format_fix_partial
else
format: format_full
format_fix: format_fix_full
endif

RUN_FORMAT ?= $(LINT_RUNNER) prettier-eslint
format_full:
	$(RUN_FORMAT) '$(PWD)/**/*.{js,less}' --list-different
format_fix_full:
	$(RUN_FORMAT) '$(PWD)/**/*.{js,less}' --write

format_partial:
ifneq (,$(FILES_FOR_LINT))
	$(RUN_FORMAT) $(FILES_FOR_FORMAT) --list-different
endif
format_fix_partial:
ifneq (,$(FILES_FOR_LINT))
	$(RUN_FORMAT) $(FILES_FOR_FORMAT) --write
endif
{% endblock %}


UNIT_TEST_DOCKER_COMPOSE ?= \
	COMPOSE_PROJECT_NAME=unit_test_$(BUILD_DIR_NAME) $(DOCKER_COMPOSE)

test: test_unit
test_unit: test_unit_app
test_unit_app:
{% if has_unit_tests %}
	$(UNIT_TEST_DOCKER_COMPOSE) run --rm test_unit
	$(MAKE) clean_test_unit_app
{% endif %}

clean_ci: clean_test_unit
clean_test_unit: clean_test_unit_app
clean_test_unit_app:
{% if has_unit_tests %}
	$(UNIT_TEST_DOCKER_COMPOSE) down --timeout 0
{% endif %}


ACCEPTANCE_TEST_DOCKER_COMPOSE ?= \
	COMPOSE_PROJECT_NAME=acceptance_test_$(BUILD_DIR_NAME) $(DOCKER_COMPOSE)

test: test_acceptance
test_acceptance: test_acceptance_app
test_acceptance_run: test_acceptance_app_run
test_acceptance_app: clean_test_acceptance_app
test_acceptance_app: test_acceptance_app_run

{% block test_acceptance %}
test_acceptance_app_run:
{% if has_acceptance_tests %}
	$(ACCEPTANCE_TEST_DOCKER_COMPOSE) run --rm test_acceptance
	$(MAKE) clean_test_acceptance_app
{% endif %}
{% endblock %}

test_acceptance_app_run: test_acceptance_pre_run
test_acceptance_pre_run:
{% if has_pre_test_acceptance %}
	$(ACCEPTANCE_TEST_DOCKER_COMPOSE) run --rm \
		--entrypoint bash \
	 	test_acceptance \
	 		test/acceptance/scripts/pre-run
{% endif %}
{% if 'minio' in dependencies %}
	$(ACCEPTANCE_TEST_DOCKER_COMPOSE) up minio_setup
{% endif %}

clean_ci: clean_test_acceptance
clean_test_acceptance: clean_test_acceptance_app
clean_test_acceptance_app:
{% if has_acceptance_tests %}
	$(ACCEPTANCE_TEST_DOCKER_COMPOSE) down --volumes --timeout 0
{% endif %}

{% block clean_test_acceptance %}
{% endblock %}


{% if has_frontend_tests %}
FRONTEND_DOCKER_COMPOSE ?= \
	COMPOSE_PROJECT_NAME=frontend_$(BUILD_DIR_NAME) $(DOCKER_COMPOSE)

build_test_frontend:
{%   if not has_karma_tests %}
	$(FRONTEND_DOCKER_COMPOSE) build --force-rm test_frontend
{%   endif %}

test: test_frontend
test_frontend: test_frontend_build_run
test_frontend_build_run: build_test_frontend
test_frontend_build_run: test_frontend_run

test_frontend_run:
	$(FRONTEND_DOCKER_COMPOSE) run --rm test_frontend
	$(FRONTEND_DOCKER_COMPOSE) down -t 0

clean_test_acceptance: clean_test_frontend
clean_test_frontend:
{%   if has_karma_tests %}
	$(FRONTEND_DOCKER_COMPOSE) down
{%   else %}
	$(FRONTEND_DOCKER_COMPOSE) down --rmi local
{%   endif %}
{% endif %}

{% if has_karma_tests %}
KARMA_DOCKER_COMPOSE ?= \
	COMPOSE_PROJECT_NAME=karma_$(BUILD_DIR_NAME) $(DOCKER_COMPOSE)

test_karma_build: build_test_karma
build_test_karma:
	$(KARMA_DOCKER_COMPOSE) build --force-rm test_karma

test: test_karma
test_karma: test_karma_build_run
test_karma_build_run: build_test_karma
test_karma_build_run: test_karma_run

test_karma_run:
	$(KARMA_DOCKER_COMPOSE) run --rm test_karma
	$(KARMA_DOCKER_COMPOSE) down -t 0

clean_test_acceptance: clean_test_karma
clean_test_karma:
	$(KARMA_DOCKER_COMPOSE) down --rmi local
{% endif %}


{% block build_app %}
build_app:
{% endblock %}

{% if has_app_views %}
# GNU Makes wildcard pattern '**' does not match empty or deep components
VIEW_FILES:=$(shell \
	find app/views modules/*/app/views -name '*.pug' \
	| grep -v -e '/_' \
	| sed 's|^|generated/views/|;s/.pug/.js/' \
)

build_views_full:
	node build/views

build_views: $(VIEW_FILES)
.PHONY: $(VIEW_FILES)
$(VIEW_FILES): generated/views/%.js:
	node build/views $*
{% endif %}

{% if has_locales %}
build_lngs_full:
	node build/translations

LNGS = $(patsubst locales/%.json,generated/lng/%.js,$(wildcard locales/*.json))
build_lng: $(LNGS)
$(LNGS): $(wildcard build/translations/*.js)
$(LNGS): locales/en.json
$(LNGS): generated/lng/%.js: locales/%.json
	node build/translations $*

webpack_production:
	$(MAKE) --no-print-directory -j build_lng
	npm run webpack:production
{% endif %}

build_dev_deps: clean_build_artifacts
	docker build \
		--force-rm=true \
		--cache-from $(IMAGE_CI)-dev-deps-cache \
		--tag $(IMAGE_CI)-base \
		--target base \
		.

	docker build \
		--force-rm=true \
		--cache-from $(IMAGE_CI)-base \
		--cache-from $(IMAGE_CI)-dev-deps-cache \
		--tag $(IMAGE_CI)-dev-deps \
		--target dev-deps \
		.

build_dev: clean_build_artifacts
	docker build \
		--force-rm=true \
		--cache-from $(IMAGE_CI)-dev-deps \
		--tag $(IMAGE_CI)-dev \
		--target dev \
		.

{% if has_webpack_config_js %}
build_webpack: clean_build_artifacts
	docker build \
		--force-rm=true \
		--cache-from $(IMAGE_CI)-dev \
		--tag $(IMAGE_CI)-webpack \
		--target webpack \
		.
{% endif %}

build_prod: clean_build_artifacts
	docker build \
		--force-rm=true \
{% if has_webpack_config_js %}
		--cache-from $(IMAGE_CI)-webpack \
{% else %}
		--cache-from $(IMAGE_CI)-dev \
{% endif %}
		--tag $(IMAGE_CI)-base \
		--target base \
		.

	docker run \
		--rm \
{% if has_webpack_config_js %}
		$(IMAGE_CI)-webpack \
{% else %}
		$(IMAGE_CI)-dev \
{% endif %}
		$(TAR_CREATE_REPRODUCIBLE) \
{% if has_index_js %}
			index.js \
{% endif %}
{% if has_app_js %}
			app.js \
{% endif %}
{% if has_app_src %}
			app/{{ src_dir }} \
{% endif %}
{% if has_app_lib %}
			app/lib \
{% endif %}
{% if has_app_templates %}
			app/templates \
{% endif %}
{% if has_app_views %}
			app/views \
{% endif %}
{% if has_config %}
			config \
{% endif %}
{% if has_locales %}
			generated/lng/ \
{% endif %}
{% if has_app_views %}
			generated/views/ \
{% endif %}
{% if has_modules %}
			modules/*/app/ \
			modules/*/index.js \
{% endif %}
{% if has_webpack_config_js %}
			{{ webpack_public_path|default('public/js') }}/manifest.json \
{% endif %}
{% block build_artifacts %}
{% endblock %}
{% if has_entrypoint %}
			entrypoint.sh \
{% endif %}
{% if has_setup_env %}
			setup_env.sh \
{% endif %}
{% if has_smoke_tests %}
			test/smoke/{{ src_dir }} \
{% endif %}
	| gzip \
	> build_artifacts.tar.gz
	$(TOUCH_REPRODUCIBLE) build_artifacts.tar.gz

	docker build \
		--force-rm=true \
		--build-arg RELEASE=$(RELEASE) \
		--build-arg COMMIT=$(COMMIT) \
		--build-arg BASE=$(IMAGE_CI)-base \
		--cache-from $(IMAGE_CI)-base \
		--cache-from $(IMAGE_CI)-prod-cache \
		--tag $(IMAGE_CI)-prod \
		--file=Dockerfile.production \
		.

clean_build: clean_build_artifacts
clean_build_artifacts:
	rm -f build_artifacts.tar.gz


clean_ci: clean_output
clean_output:
ifneq (,$(wildcard output/* output/.*))
	docker run --rm \
		--volume $(PWD)/output:/home/node \
		--user node \
		--network none \
		$(IMAGE_NODE) \
		sh -c 'find /home/node -mindepth 1 | xargs rm -rfv'
	rm -rfv output
endif

{# CI helper #}
pull_node:
	docker pull $(IMAGE_NODE)
	docker tag $(IMAGE_NODE) node:{{ node_version }}

pull_cache_cold:
	docker pull $(IMAGE_CACHE_COLD)$(R_TARGET)
	docker tag $(IMAGE_CACHE_COLD)$(R_TARGET) $(IMAGE_CI)$(TARGET)-cache

pull_cache_hot:
	docker pull $(IMAGE_CACHE_HOT)$(R_TARGET)
	docker tag $(IMAGE_CACHE_HOT)$(R_TARGET) $(IMAGE_CI)$(TARGET)-cache

pull_cache:
	make pull_cache_hot || make pull_cache_cold || echo 'cache miss'

clean_pull_cache:
	docker rmi --force \
		$(IMAGE_CACHE_COLD)$(R_TARGET) \
		$(IMAGE_CACHE_HOT)$(R_TARGET) \


push_cache_hot:
	docker tag $(IMAGE_CI)$(TARGET) $(IMAGE_CACHE_HOT)$(R_TARGET)
	docker push $(IMAGE_CACHE_HOT)$(R_TARGET)

push_target:
	docker tag $(IMAGE_CI)$(TARGET) $(IMAGE)$(R_TARGET)
	docker push $(IMAGE)$(R_TARGET)

clean_push:
	docker rmi --force \
		$(IMAGE)$(R_TARGET) \
		$(IMAGE_CACHE_HOT)$(R_TARGET) \


prepare_ci_stage: build_dev_with_cache
build_dev_with_cache: pull_node
build_dev_with_cache:
	docker pull $(IMAGE)-dev-deps
	docker tag $(IMAGE)-dev-deps $(IMAGE_CI)-dev-deps
	$(MAKE) --no-print-directory build_dev

prepare_ci_stage: create_output
create_output:
	mkdir --parents --mode=777 output

clean_ci_stage: clean_output
clean_ci_stage: clean_stage_images
clean_stage_images:
	docker rmi --force \
		$(IMAGE)-dev-deps \
		$(IMAGE_CI)-dev-deps \
		$(IMAGE_CI)-dev \

{% if has_webpack_config_js %}
compress_public: public.tar.gz
.PHONY: public.tar.gz
public.tar.gz:
	docker run \
		--rm \
		--volume $(PWD)/compress.sh:/compress.sh \
		--workdir /app/public \
		--entrypoint sh \
		$(IMAGE_CI)-webpack \
		-c '/compress.sh && $(TAR_CREATE_REPRODUCIBLE) .' \
	| gzip -9 \
	> public.tar.gz
	sha256sum public.tar.gz | awk '{ print $$1 }' > public.tar.gz.checksum.txt
	$(TOUCH_REPRODUCIBLE) public.tar.gz public.tar.gz.checksum.txt
{% endif %}

{% if name == 'real-time' %}
socket.io-client: public.tar.gz
.PHONY: public.tar.gz
public.tar.gz:
	docker run \
		--rm \
		--volume $(PWD)/compress.sh:/compress.sh \
		--workdir /app/node_modules/socket.io-client/dist/ \
		--user root \
		--entrypoint sh \
		$(IMAGE_CI)-prod \
		-c 'rm *.swf && /compress.sh && $(TAR_CREATE_REPRODUCIBLE) .' \
	| gzip -9 \
	> public.tar.gz
	sha256sum public.tar.gz | awk '{ print $$1 }' > public.tar.gz.checksum.txt
	$(TOUCH_REPRODUCIBLE) public.tar.gz public.tar.gz.checksum.txt
{% endif %}

{% if has_modules %}
MODULE_DIRS := $(shell find modules -mindepth 1 -maxdepth 1 -type d -not -name '.git' )
MODULE_MAKEFILES := $(MODULE_DIRS:=/Makefile)

$(MODULE_MAKEFILES): Makefile.module
	cp Makefile.module $@

clean: clean_Makefiles
clean_Makefiles:
	rm -f $(MODULE_MAKEFILES)

test_acceptance: test_acceptance_modules
test_acceptance_run: test_acceptance_modules_run
test_acceptance_modules: test_acceptance_modules_run
TEST_ACCEPTANCE_MODULES = $(addsuffix /test_acceptance,$(MODULE_DIRS))
test_acceptance_modules_run: $(TEST_ACCEPTANCE_MODULES)

TEST_ACCEPTANCE_CI_MODULES = $(addsuffix /test_acceptance_ci,$(MODULE_DIRS))
test_acceptance_modules_run_ci: $(TEST_ACCEPTANCE_CI_MODULES)

clean_test_acceptance: clean_test_acceptance_modules
CLEAN_TEST_ACCEPTANCE_MODULES = $(addsuffix /clean_test_acceptance,$(MODULE_DIRS))
clean_test_acceptance_modules: $(CLEAN_TEST_ACCEPTANCE_MODULES)

test_unit: test_unit_modules
test_unit_run: test_unit_modules_run
test_unit_modules: test_unit_modules_run
TEST_UNIT_MODULES = $(addsuffix /test_unit,$(MODULE_DIRS))
test_unit_modules_run: $(TEST_UNIT_MODULES)

TEST_UNIT_CI_MODULES = $(addsuffix /test_unit_ci,$(MODULE_DIRS))
test_unit_modules_run_ci: $(TEST_UNIT_CI_MODULES)

clean_test_unit: clean_test_unit_modules
CLEAN_TEST_UNIT_MODULES = $(addsuffix /clean_test_unit,$(MODULE_DIRS))
clean_test_unit_modules: $(CLEAN_TEST_UNIT_MODULES)

MODULE_TARGETS = \
	$(TEST_ACCEPTANCE_MODULES) \
	$(TEST_ACCEPTANCE_CI_MODULES) \
	$(CLEAN_TEST_ACCEPTANCE_MODULES) \
	$(TEST_UNIT_MODULES) \
	$(TEST_UNIT_CI_MODULES) \
	$(CLEAN_TEST_UNIT_MODULES) \

$(MODULE_TARGETS): $(MODULE_MAKEFILES)
	$(MAKE) -C $(dir $@) $(notdir $@)

.PHONY: $(MODULE_TARGETS)
{% endif %}

.PHONY: clean test test_unit test_acceptance test_clean build
