{% from 'macros/header.j2' import header with context %}
{{ header('#') }}
{% set label_docker_image = '$(PROJECT_NAME):$(BRANCH_NAME)-$(BUILD_NUMBER)' %}

BUILD_NUMBER ?= local
BRANCH_NAME ?= $(shell git rev-parse --abbrev-ref HEAD)
COMMIT ?= $(shell git rev-parse HEAD)
RELEASE ?= $(shell git describe --tags | sed 's/-g/+/;s/^v//')
PROJECT_NAME = {{ name }}
{% if 'minio' in dependencies %}
S3_ENDPOINT ?= http://minio:9000
S3_FORCE_PATH_STYLE ?= true
AWS_KEY ?= $(shell openssl rand -hex 20)
AWS_SECRET ?= $(shell openssl rand -hex 20)
{%   if name == 'filestore' %}
BACKEND ?= fs
S3_BACKEND ?= aws-sdk
AWS_BUCKET_USER ?= user
AWS_BUCKET_TEMPLATE ?= template
AWS_BUCKET_PUBLIC ?= public
{%   else %}
AWS_BUCKET ?= bucket
{%   endif %}
{% endif %}
DOCKER_COMPOSE_FLAGS ?= -f docker-compose.yml
DOCKER_COMPOSE := BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH_NAME=$(BRANCH_NAME) \
	PROJECT_NAME=$(PROJECT_NAME) \
	MOCHA_GREP=${MOCHA_GREP} \
{% if acceptance_creds == 'aws' %}
	AWS_BUCKET=${AWS_BUCKET} \
	AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
	AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
{% endif %}
{% if 'minio' in dependencies %}
	S3_ENDPOINT=$(S3_ENDPOINT) \
	S3_FORCE_PATH_STYLE=$(S3_FORCE_PATH_STYLE) \
	AWS_KEY=$(AWS_KEY) \
	AWS_SECRET=$(AWS_SECRET) \
{%   if name == 'filestore' %}
	BACKEND=$(BACKEND) \
	S3_BACKEND=$(S3_BACKEND) \
	AWS_BUCKET_USER=$(AWS_BUCKET_USER) \
	AWS_BUCKET_TEMPLATE=$(AWS_BUCKET_TEMPLATE) \
	AWS_BUCKET_PUBLIC=$(AWS_BUCKET_PUBLIC) \
{%   else %}
	AWS_BUCKET=$(AWS_BUCKET) \
{%   endif %}
{% endif %}
	docker-compose ${DOCKER_COMPOSE_FLAGS}

clean_ci: clean
clean_ci: clean_build
clean_ci: test_clean

clean_build:
	docker rmi \
		ci/{{ label_docker_image }} \
		ci/{{ label_docker_image }}-base \
		ci/{{ label_docker_image }}-dev \
		ci/{{ label_docker_image }}-prod \
		ci/{{ label_docker_image }}-cache \
		--force

clean:
{% block clean %}
{% endblock %}

test: lint
lint:
{% block lint %}
	$(DOCKER_COMPOSE) run --rm test_unit npm run lint
{% endblock %}

{% block test %}
{% endblock %}

test: test_unit
test_unit:
{% if has_unit_tests %}
	$(DOCKER_COMPOSE) run --rm test_unit
{% endif %}

test: test_acceptance
test_acceptance: test_clean test_acceptance_pre_run test_acceptance_run

test_acceptance_run:
{% if has_acceptance_tests %}
	$(DOCKER_COMPOSE) run --rm test_acceptance
{% endif %}

{% block clean_test_acceptance %}
clean_test_acceptance:
{% endblock %}

test_clean:
	$(DOCKER_COMPOSE) down -v -t 0

test_acceptance_pre_run:
{% if has_pre_test_acceptance %}
	$(DOCKER_COMPOSE) run --rm --entrypoint bash test_acceptance test/acceptance/scripts/pre-run
{% endif %}
{% if 'minio' in dependencies %}
	$(DOCKER_COMPOSE) up -d minio_setup minio
{% endif %}

{% block build_app %}
build_app:
{% endblock %}

build: clean_build_artifacts
	docker build \
		--cache-from ci/{{ label_docker_image }}-cache \
		--tag ci/{{ label_docker_image }}-base \
		--target base \
		.

	docker build \
		--cache-from ci/{{ label_docker_image }}-base \
		--tag ci/{{ label_docker_image }} \
		--tag ci/{{ label_docker_image }}-dev \
		--target dev \
		.

build_prod: clean_build_artifacts
	docker run \
		--rm \
		--entrypoint tar \
		ci/{{ label_docker_image }}-dev \
			--create \
			--gzip \
{% if has_index_js %}
			index.js \
{% endif %}
{% if has_app_js %}
			app.js \
{% endif %}
{% if has_app_src %}
			app/{{ src_dir }} \
{% endif %}
{% if has_app_lib %}
			app/lib \
{% endif %}
{% if has_app_templates %}
			app/templates \
{% endif %}
{% if has_app_views %}
			app/views \
{% endif %}
{% if has_config %}
			config \
{% endif %}
{% block build_artifacts %}
{% endblock %}
{% if has_entrypoint %}
			entrypoint.sh \
{% endif %}
{% if has_setup_env %}
			setup_env.sh \
{% endif %}
{% if has_smoke_tests %}
			test/smoke/{{ src_dir }} \
{% endif %}
		> build_artifacts.tar.gz

	docker build \
		--build-arg RELEASE=$(RELEASE) \
		--build-arg COMMIT=$(COMMIT) \
		--build-arg BASE=ci/{{ label_docker_image }}-base \
		--cache-from ci/{{ label_docker_image }}-cache \
		--tag ci/{{ label_docker_image }}-prod \
		--file=Dockerfile.production \
		.

clean_ci: clean_build_artifacts
clean_build_artifacts:
	rm -f build_artifacts.tar.gz

.PHONY: clean test test_unit test_acceptance test_clean build
