FROM node:{{ node_version }} as app

{% block app %}
WORKDIR /app

#wildcard as some files may not be in all repos
COPY package*.json npm-shrink*.json /app/

RUN npm install --quiet

COPY . /app


{% endblock %}

FROM node:{{ node_version }}

{% block runtime %}
COPY --from=app /app /app

WORKDIR /app
{% if has_install_deps %}
RUN chmod 0755 ./install_deps.sh && ./install_deps.sh
{% endif %}
{% if has_entrypoint %}
ENTRYPOINT ["/bin/sh", "entrypoint.sh"]
{% else %}
USER node
{% endif %}

CMD ["node", "--expose-gc", "app.js"]
{% endblock %}
