{% from 'macros/header.j2' import header with context %}
{{ header('#') }}
{% set label_docker_image = '$(PROJECT_NAME):$(BRANCH_NAME)-$(BUILD_NUMBER)' %}

BUILD_NUMBER ?= local
BRANCH_NAME ?= $(shell git rev-parse --abbrev-ref HEAD)
PROJECT_NAME = {{ name }}
DOCKER_COMPOSE_FLAGS ?= -f docker-compose.yml
DOCKER_COMPOSE := BUILD_NUMBER=$(BUILD_NUMBER) \
	BRANCH_NAME=$(BRANCH_NAME) \
	PROJECT_NAME=$(PROJECT_NAME) \
	MOCHA_GREP=${MOCHA_GREP} \
{% if acceptance_creds == 'aws' %}
	AWS_BUCKET=${AWS_BUCKET} \
	AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
	AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
{% endif %}
	docker-compose ${DOCKER_COMPOSE_FLAGS}

clean:
{% block clean %}
	docker rmi ci/{{ label_docker_image }}
	docker rmi {{ docker_repos }}/{{ label_docker_image }}
{%- endblock %}

{% block lint %}
lint:
	$(DOCKER_COMPOSE) run --rm test_unit npm run lint

{% endblock %}
{% block test %}
test: lint test_unit test_acceptance
{% endblock %}

test_unit:
	@[ ! -d test/unit ] && echo "{{ name }} has no unit tests" || $(DOCKER_COMPOSE) run --rm test_unit

test_acceptance: test_clean test_acceptance_pre_run test_acceptance_run

test_acceptance_run:
	@[ ! -d test/acceptance ] && echo "{{ name }} has no acceptance tests" || $(DOCKER_COMPOSE) run --rm test_acceptance

test_clean:
	$(DOCKER_COMPOSE) down -v -t 0

test_acceptance_pre_run:
	@[ ! -f test/acceptance/scripts/pre-run ] && echo "{{ name }} has no pre acceptance tests task" || $(DOCKER_COMPOSE) run --rm test_acceptance test/acceptance/scripts/pre-run
build:
	docker build --pull --tag ci/{{ label_docker_image }} \
		--tag {{ docker_repos }}/{{ label_docker_image }} \
		.

tar:
	$(DOCKER_COMPOSE) up tar

publish:

	docker push $(DOCKER_REPO)/{{ label_docker_image }}

.PHONY: clean test test_unit test_acceptance test_clean build publish
