{% extends '_/coffeescript/Makefile.j2' %}

{% block clean_test_acceptance %}
clean_test_acceptance: clean_clsi_artifacts
clean_test_acceptance_app: clean_clsi_artifacts
clean_clsi_artifacts:
	$(ACCEPTANCE_TEST_DOCKER_COMPOSE) run --rm \
		--entrypoint bash \
		test_acceptance \
			-c 'rm -rf \
				/app/cache/* \
				/app/compiles/* \
			'
{% endblock %}

{% block build_artifacts %}
			seccomp \
			bin/synctex \
{% endblock %}
