{% extends '_/coffeescript/Makefile.j2' %}

{% block test_acceptance %}
export TEXLIVE_IMAGE ?= quay.io/sharelatex/texlive-full:2017.1

test_acceptance_app: pull_texlive
pull_texlive:
	docker pull $(TEXLIVE_IMAGE)

ifeq (true,$(PULL_TEXLIVE_BEFORE_RUN))
test_acceptance_app_run: pull_texlive
endif

{{ super() }}
{% endblock %}

{% block clean_test_acceptance %}
clean_test_acceptance: clean_clsi_artifacts
clean_test_acceptance_app: clean_clsi_artifacts
clean_clsi_artifacts:
	docker run --rm \
		--volume $(PWD)/cache:/app/cache:z \
		--volume $(PWD)/compiles:/app/compiles:z \
		--network none \
		$(IMAGE_NODE) \
		sh -c 'rm -rf /app/cache/* app/compiles/*'
{% endblock %}

{% block build_artifacts %}
			seccomp \
			bin/synctex \
{% endblock %}
