{% extends 'es/Makefile.j2' %}

{% block lint %}
{% endblock %}

{% block clean %}
{{ super() }}
	rm -f app.js
	rm -rf app/js
	rm -rf test/unit/js
	rm -rf test/acceptance/js
{% endblock %}

{% set test_deps = [
	'test_unit',
	'test_acceptance',
	] %}
